### ISSUE TITLE
Atom fields for booleans

### ISSUE THREAD

**Issue by tucotuco** [VertNet/dwc-indexer#20]
Check to see that the following optimization is in place. If not, amend it.

From https://developers.google.com/appengine/docs/python/search/best_practices:
"Use atom fields for boolean data
Storing boolean data in number fields is very inefficient. Use atom fields instead, and assign your favorite constants (True/False, yes/no, 0/1)."

**Comment by tucotuco** [comment]
Worth investigating again to see if it helps with queries timing out when many "boolean" fields are used alone.  Set all "boolean" fields to Atom. Set all fields that a search would be on the complete content rather than a part to Atom.

**Comment by dbloom** [comment]
Will a change like this have an affect on the monthly charges for use?

**Comment by tucotuco** [comment]
Should reduce them.

**Comment by tucotuco** [comment]
Implemented and tested in commit ba170b49bf28813a5d23c62d7064f8470c0cf0e1. Works well.
