### ISSUE TITLE
Record Type flags

### ISSUE THREAD

**Issue by laurarussell** [VertNet/dwc-indexer#26]
In writing documentation for advanced search terms, we've been reviewing the code for how some things work.  With record type, it seems that this code to flag the records in indexing could be miss interpreting the record type.

from: https://github.com/VertNet/dwc-indexer/blob/c53163acd8bd1fbb0e6effb4b34c4e07aa2b8b7e/utils.py#L316

def _type(rec):
    """Return one of 'specimen', 'observation', or 'both' based on content of the type and basisofrecord fields."""
    if rec.has_key('type'):
        if rec['type'].lower() == 'physicalobject':
            return 'specimen'
        return 'observation'
    if rec.has_key('basisofrecord'):
        if 'spec' in rec['basisofrecord'].lower():
            return 'specimen'
        return 'observation'
    return 'both'

In review of the code, @tucotuco and I came to the conclusion we can be more explicit by using basisOfRecord as basisOfRecord is required for data sets published with IPT.  This section will need to be recoded using basisOfRecord.  Some additional changes will need to be made to the code on the search options in the portal. See https://github.com/VertNet/webapp/issues/509

**Comment by tucotuco** [comment]
Though basisOfRecord is required in theory, OMNH has for resources with both basisOfRecord and type as null.

Refactoring the _type method to be based on basisOfRecord first, then type, but otherwise exactly the same functionality in the portal.

Adding basisOfRecord and type (as 'dctype') to the index as well.
