### ISSUE TITLE
Add a new index field for portal.vertnet.org URL to specimen detail page

### ISSUE THREAD

**Issue by mkoo** [VertNet/dwc-indexer#29]
Notes: parse keyname to the URL

**Comment by tucotuco** [comment]
Added the dc:references field to the harvest and the index. This is the field that is meant to contain a linkback to a detail record. For those who do not provide their own at the source, this is is currently provided in the migrators. If the data are not migrated and there is no references field, or it is empty, the indexer will provide it based on the patterm 

```
reference = 'http://portal.vertnet.org/o/%s/%s?id=%s' % (icode_slug, coll_id, occ_id)
```
